name: "vident"

services:
  vident-dev-env:
    container_name: vident-dev-env
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "3200"
    volumes:
      - vscode-home:/home/vscode

volumes:
  vscode-home: